import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Fake Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="px-8 sticky top-0 flex items-center shadow-md bg-white z-10">
          <Link href="/">
            <h1 className="text-3xl font-bold my-8">Fake Store</h1>
          </Link>
        </header>
        <main className="p-8 row-start-2 w-full z-0">{children}</main>
      </body>
    </html>
  );
}
